version: '3.7'
services:
  app:
    build:
      context: .
      args:
        - APP_PORT=8080
    links:
      - json_server
    ports:
      - '8080:8080'
    volumes:
      - .:/app
  json_server:
    build:
      context: docker/json-server
      args:
        - APP_PORT=3000
    ports:
      - '3000:3000'
    volumes:
      - ${PWD}/docker/json-server/db.json:/app/db.json
